# Generated by Django 5.2.5 on 2025-09-26 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0008_alter_multiplayerplayer_player"),
    ]

    operations = [
        migrations.AddField(
            model_name="multiplayerplayer",
            name="guest_name",
            field=models.CharField(max_length=20, null=True),
        ),
    ]
