# Generated by Django 5.2.7 on 2025-10-03 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_session_multiplayergame_session'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='first_to',
            field=models.IntegerField(null=True),
        ),
    ]
