# Generated by Django 5.2.7 on 2025-11-01 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0011_session_first_to"),
    ]

    operations = [
        migrations.AddField(
            model_name="multiplayergame",
            name="one_device_manage",
            field=models.BooleanField(default=False),
        ),
    ]
