# Generated by Django 5.2.7 on 2025-11-15 14:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0013_preferredkeyboard"),
    ]

    operations = [
        migrations.AddField(
            model_name="preferredkeyboard",
            name="guest_player",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="keyboard",
                to="main.multiplayerplayer",
            ),
        ),
    ]
