# Generated by Django 5.2.7 on 2025-11-15 15:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0014_preferredkeyboard_guest_player"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="preferredkeyboard",
            name="player",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="keyboard",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
