# Generated by Django 5.2.7 on 2025-11-21 15:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0016_multiplayerround_needed_darts_round_needed_darts_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="game",
            name="tried_doubles",
            field=models.IntegerField(
                default=0, validators=[django.core.validators.MinValueValidator(0)]
            ),
        ),
        migrations.AddField(
            model_name="multiplayerround",
            name="tried_doubles",
            field=models.IntegerField(
                default=0, validators=[django.core.validators.MinValueValidator(0)]
            ),
        ),
    ]
