# Generated by Django 5.2.7 on 2025-11-21 16:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0017_game_tried_doubles_multiplayerround_tried_doubles"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="multiplayerround",
            name="tried_doubles",
        ),
        migrations.AddField(
            model_name="multiplayerplayer",
            name="tried_doubles",
            field=models.IntegerField(
                default=0, validators=[django.core.validators.MinValueValidator(0)]
            ),
        ),
    ]
